#postgresql configuration
spring.datasource.url=jdbc:postgresql://dpg-d8v23elckfvc73f59sn0-a.oregon-postgres.render.com/moneymanager_r0hm
spring.datasource.username=moneymanager_r0hm_user
spring.datasource.password=S0uz0F4cPx37TuYVz8wlVhB40UxkWSsO